# Generated by Django 5.0.6 on 2024-05-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerchTrackApp', '0002_alter_userinfo_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.CharField(max_length=200)),
                ('distribution_date', models.CharField(max_length=200)),
                ('order_status', models.CharField(max_length=200)),
                ('payment_method', models.CharField(max_length=200)),
                ('payment_status', models.CharField(max_length=200)),
                ('order_details_ID', models.CharField(max_length=200)),
            ],
        ),
    ]
