# Generated by Django 5.0.6 on 2024-05-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerchTrackApp', '0003_order_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_info',
            name='user_info_ID',
            field=models.CharField(default='000000000', max_length=9),
        ),
    ]
