# Generated by Django 5.0.6 on 2024-05-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerchTrackApp', '0004_order_info_user_info_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_details_ID', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('item_size', models.CharField(max_length=200)),
                ('item_color', models.CharField(max_length=200)),
                ('item_cost', models.CharField(max_length=200)),
                ('item_quantity', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='order_info',
            name='order_details_ID',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
